import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../bloc/language_cubit.dart';

class AppLocalizations {
  static const Map<String, String> _en = {
    'dashboard': 'Dashboard',
    'overview': 'Overview',
    'period': 'Period',
    'daily_revenue': 'Daily revenue',
    'top_products': 'Top products',
    'stock_alerts': 'Stock alerts',
    'revenue': 'Revenue',
    'orders': 'Orders',
    'avg_order': 'Avg order',
    'items': 'Items',
    'low_stock': 'Low stock',
    'out_of_stock': 'Out of stock',
    'scan_barcode': 'Scan Barcode',
    'align_barcode': 'Align barcode within frame',
    'camera_off_title': 'Camera is turned off',
    'camera_off_subtitle':
        'Turn on your camera to start scanning barcodes and items automatically.',
    'turn_on_camera': 'Turn on Camera',
    'review_order': 'Review Order',
    'confirm_order': 'Confirm Order',
    'print_receipt': 'Print Receipt',
    'done_skip_printing': 'Done, skip printing',
    'settings': 'Settings',
    'products': 'Products',
    'shop_details': 'Shop Details',
    'sales_history': 'Sales History',
    'change_pin': 'Change PIN',
    'print_device': 'Print Device',
    'management': 'Management',
    'security': 'Security',
    'hardware': 'Hardware',
    'language_section': 'Language',
    'urdu_mode': 'Urdu Mode',
    'show_app_in_urdu': 'Show app text in Urdu',
    'manage_products': 'Manage stock and barcodes',
    'edit_shop_info': 'Edit business info & address',
    'view_sales_transactions': 'View past transactions',
    'update_pin': 'Update your login PIN',
    'no_printer_connected': 'No printer connected',
    'connected_to_printer': 'Connected to printer',
    'connected_status': 'CONNECTED',
    'dashboard_description': 'View sales and stock summaries',
    'scan_to_search': 'Tap the icon to open camera scanner',
    'product_management': 'Product Management',
    'search_or_scan': 'Search or scan barcode',
    'tap_scanner': 'Tap the icon to open camera scanner',
    'scanned_items': 'Scanned Items',
    'items_total': 'items total',
    'total_price': 'TOTAL PRICE',
    'list_is_empty': 'List is empty',
    'scan_to_pay': 'Scan to Pay',
    'grand_total': 'GRAND TOTAL',
    'product_name': 'Product Name',
    'price': 'Price',
    'total': 'Total',
    'order_confirmed_stock': 'Order confirmed! Stock updated.',
    'printed_successfully': 'Printed successfully!',
    'welcome_back': 'Welcome Back',
    'create_pin': 'Create a 4-digit PIN',
    'enter_pin': 'Enter your PIN',
    'confirm_pin': 'Confirm PIN',
    'wrong_pin': 'Wrong PIN. Try again.',
    'pin_not_match': 'PINs did not match. Try again.',
    'scan_items_instruction':
        'Scanned items will appear here as you scan them with the camera above.',
    'save_pin_success': 'PIN changed successfully',
    'enter_current_pin': 'Enter your current PIN',
    'enter_new_pin': 'Enter your new PIN',
    'confirm_new_pin': 'Confirm your new PIN',
    'change_pin_title': 'Change PIN',
    'enter_pin_setup': 'Confirm your PIN',
    'no_products': 'No products found. Add some!',
    'no_sales': 'No sales yet',
    'scanner_left': 'Align barcode within frame',
  };

  static const Map<String, String> _ur = {
    'dashboard': 'ڈیش بورڈ',
    'overview': 'جائزہ',
    'period': 'دورانیہ',
    'daily_revenue': 'روزانہ آمدنی',
    'top_products': 'مقبول اشیاء',
    'stock_alerts': 'اسٹاک الرٹ',
    'revenue': 'آمدنی',
    'orders': 'آرڈرز',
    'avg_order': 'اوسط آرڈر',
    'items': 'اشیاء',
    'low_stock': 'کم اسٹاک',
    'out_of_stock': 'اسٹاک ختم',
    'scan_barcode': 'بارکوڈ اسکین کریں',
    'align_barcode': 'بارکوڈ کو فریم میں رکھیں',
    'camera_off_title': 'کیمرہ بند ہے',
    'camera_off_subtitle': 'بارکوڈ اسکین کرنے کے لیے اپنا کیمرہ آن کریں۔',
    'turn_on_camera': 'کیمرہ آن کریں',
    'review_order': 'آرڈر چیک کریں',
    'confirm_order': 'آرڈر کی تصدیق کریں',
    'print_receipt': 'رسید پرنٹ کریں',
    'done_skip_printing': 'ہو گیا، پرنٹ نہ کریں',
    'settings': 'سیٹنگز',
    'products': 'مصنوعات',
    'shop_details': 'دکان کی تفصیلات',
    'sales_history': 'سیلز ہسٹری',
    'change_pin': 'پن تبدیل کریں',
    'print_device': 'پرنٹر ڈیوائس',
    'management': 'مینجمنٹ',
    'security': 'سیکیورٹی',
    'hardware': 'ہارڈویئر',
    'language_section': 'زبان',
    'urdu_mode': 'اردو موڈ',
    'show_app_in_urdu': 'ایپ کے متن کو اردو میں دکھائیں',
    'manage_products': 'اسٹاک اور بارکوڈز مینیج کریں',
    'edit_shop_info': 'کاروباری معلومات اور پتہ تبدیل کریں',
    'view_sales_transactions': 'گزشتہ لین دین دیکھیں',
    'update_pin': 'اپنا لاگ ان پن اپڈیٹ کریں',
    'no_printer_connected': 'کوئی پرنٹر منسلک نہیں',
    'connected_to_printer': 'پرنٹر سے منسلک',
    'connected_status': 'کنیکٹڈ',
    'dashboard_description': 'فروخت اور اسٹاک کا خلاصہ دیکھیں',
    'scan_to_search': 'کیمرہ اسکین کھولنے کے لیے آئیکن پر ٹیپ کریں',
    'product_management': 'پروڈکٹ مینجمنٹ',
    'search_or_scan': 'بارکوڈ تلاش کریں یا اسکین کریں',
    'tap_scanner': 'کیمرہ اسکین کھولنے کے لیے آئیکن پر ٹیپ کریں',
    'scanned_items': 'سکین کی گئی اشیاء',
    'items_total': 'اشیاء کل',
    'total_price': 'کل قیمت',
    'list_is_empty': 'فہرست خالی ہے',
    'scan_to_pay': 'ادائیگی کے لیے اسکین کریں',
    'grand_total': 'کل رقم',
    'product_name': 'پروڈکٹ کا نام',
    'price': 'قیمت',
    'total': 'کل',
    'order_confirmed_stock': 'آرڈر کی تصدیق ہوگئی! اسٹاک اپ ڈیٹ ہوگیا۔',
    'printed_successfully': 'کامیابی سے پرنٹ ہوچکا ہے!',
    'welcome_back': 'خوش آمدید',
    'create_pin': '4 ہندسے کا پن بنائیں',
    'enter_pin': 'اپنا پن درج کریں',
    'confirm_pin': 'پن کی تصدیق کریں',
    'wrong_pin': 'غلط پن۔ دوبارہ کوشش کریں۔',
    'pin_not_match': 'پن میل نہیں کھا رہے۔ دوبارہ کوشش کریں۔',
    'scan_items_instruction':
        'بارکوڈ کو اوپر کیمرہ میں اسکین کریں، آئٹمز یہاں دکھیں گے۔',
    'save_pin_success': 'پن کامیابی سے تبدیل ہوگیا',
    'enter_current_pin': 'اپنا موجودہ پن درج کریں',
    'enter_new_pin': 'اپنا نیا پن درج کریں',
    'confirm_new_pin': 'اپنے نئے پن کی تصدیق کریں',
    'change_pin_title': 'پن تبدیل کریں',
    'enter_pin_setup': 'اپنے پن کی تصدیق کریں',
    'no_products': 'کوئی مصنوعات نہیں ملی۔ کچھ شامل کریں!',
    'no_sales': 'ابھی تک کوئی سیلز نہیں',
    'scanner_left': 'بارکوڈ کو فریم میں رکھیں',
  };

  static String translate(BuildContext context, String key) {
    final language = context.watch<LanguageCubit>().state;
    return (language == AppLanguage.urdu ? _ur : _en)[key] ?? _en[key] ?? key;
  }
}

extension TranslateExtension on BuildContext {
  String tr(String key) => AppLocalizations.translate(this, key);
  bool get isUrdu => watch<LanguageCubit>().state == AppLanguage.urdu;
}
