import 'package:flutter/widgets.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import '../bloc/language_cubit.dart';

class AppLocalizations {
  static const Map<String, String> _en = {
    'dashboard': 'Dashboard',
    'overview': 'Overview',
    'period': 'Period',
    'daily_revenue': 'Daily revenue',
    'top_products': 'Top products',
    'stock_alerts': 'Stock alerts',
    'revenue': 'Revenue',
    'orders': 'Orders',
    'avg_order': 'Avg order',
    'items': 'Items',
    'low_stock': 'Low stock',
    'out_of_stock': 'Out of stock',
    'scan_barcode': 'Scan Barcode',
    'align_barcode': 'Align barcode within frame',
    'camera_off_title': 'Camera is turned off',
    'camera_off_subtitle':
        'Turn on your camera to start scanning barcodes and items automatically.',
    'turn_on_camera': 'Turn on Camera',
    'review_order': 'Review Order',
    'confirm_order': 'Confirm Order',
    'print_receipt': 'Print Receipt',
    'done_skip_printing': 'Done, skip printing',
    'settings': 'Settings',
    'products': 'Products',
    'shop_details': 'Shop Details',
    'sales_history': 'Sales History',
    'change_pin': 'Change PIN',
    'print_device': 'Print Device',
    'management': 'Management',
    'security': 'Security',
    'hardware': 'Hardware',
    'language_section': 'Language',
    'urdu_mode': 'Urdu Mode',
    'show_app_in_urdu': 'Show app text in Urdu',
    'manage_products': 'Manage stock and barcodes',
    'edit_shop_info': 'Edit business info & address',
    'view_sales_transactions': 'View past transactions',
    'update_pin': 'Update your login PIN',
    'lock_app': 'Lock App',
    'lock_app_description': 'Lock the app with PIN',
    'receipt_settings': 'Receipt Settings',
    'whatsapp_receipts': 'WhatsApp Receipts',
    'whatsapp_receipts_desc': 'Show WhatsApp sharing options after checkout',
    'no_printer_connected': 'No printer connected',
    'connected_to_printer': 'Connected to printer',
    'connected_status': 'CONNECTED',
    'dashboard_description': 'View sales and stock summaries',
    'khata_description': 'Manage customer credits and ledger (Khata)',
    'scan_to_search': 'Tap the icon to open camera scanner',
    'product_management': 'Product Management',
    'search_or_scan': 'Search or scan barcode',
    'tap_scanner': 'Tap the icon to open camera scanner',
    'scanned_items': 'Scanned Items',
    'items_total': 'items total',
    'total_price': 'TOTAL PRICE',
    'list_is_empty': 'List is empty',
    'scan_to_pay': 'Scan to Pay',
    'grand_total': 'GRAND TOTAL',
    'product_name': 'Product Name',
    'price': 'Price',
    'total': 'Total',
    'order_confirmed_stock': 'Order confirmed! Stock updated.',
    'printed_successfully': 'Printed successfully!',
    'welcome_back': 'Welcome Back',
    'create_pin': 'Create a 4-digit PIN',
    'enter_pin': 'Enter your PIN',
    'confirm_pin': 'Confirm PIN',
    'wrong_pin': 'Wrong PIN. Try again.',
    'pin_not_match': 'PINs did not match. Try again.',
    'scan_items_instruction':
        'Scanned items will appear here as you scan them with the camera above.',
    'save_pin_success': 'PIN changed successfully',
    'enter_current_pin': 'Enter your current PIN',
    'enter_new_pin': 'Enter your new PIN',
    'confirm_new_pin': 'Confirm your new PIN',
    'change_pin_title': 'Change PIN',
    'enter_pin_setup': 'Confirm your PIN',
    'no_products': 'No products found. Add some!',
    'no_sales': 'No sales yet',
    'scanner_left': 'Align barcode within frame',
    // ── WhatsApp receipt ──────────────────────────────────────────────
    'send_receipt': 'Send Receipt',
    'whatsapp_number_hint': 'Enter customer\'s WhatsApp number',
    'whatsapp_country_code_hint': 'Include country code e.g. 923001234567',
    'whatsapp_number_empty': 'Please enter a phone number',
    'whatsapp_number_short': 'Enter a valid number with country code',
    'whatsapp_not_installed': 'Could not open WhatsApp. Is it installed?',
    'cancel': 'Cancel',
    'send': 'Send',
    'share_receipt': 'Share Receipt',
    'share_as_image': 'Share as Image',
    'whatsapp': 'WhatsApp',
    // ── Receipt image content ─────────────────────────────────────────
    'receipt_title': 'RECEIPT',
    'receipt_item_header': 'ITEM',
    'receipt_qty_header': 'QTY',
    'receipt_price_header': 'PRICE',
    'receipt_total_header': 'TOTAL',
    'receipt_grand_total': 'GRAND TOTAL',
    'receipt_thank_you': 'Thank you for shopping with us!',
    'receipt_powered_by': 'Powered by BillingApp',
    // ── Khata page ────────────────────────────────────────────────────
    'khata_title': 'Khata / Udhaar',
    'total_outstanding': 'Total Outstanding',
    'customers': 'Customers',
    'no_customers_yet': 'No Customers Yet',
    'no_customers_desc':
        'Tap the button below to add your\nfirst udhaar customer.',
    'add_customer': 'Add Customer',
    'delete_customer': 'Delete Customer?',
    'delete_customer_confirm':
        'This will remove {name} and all their entries.',
    'delete': 'Delete',
    'new_customer': 'New Customer',
    'customer_name': 'Customer Name',
    'customer_name_hint': 'e.g. Ahmed Bhai',
    'customer_name_required': 'Enter customer name',
    'phone_optional': 'Phone (optional)',
    'phone_label': 'Phone Number',
    'phone_required': 'Phone number is required',
    'phone_hint': '03XX-XXXXXXX',
    'add': 'Add',
    'udhaar': 'Udhaar',
    'clear_status': 'Clear',
    // ── Customer detail page ──────────────────────────────────────────
    'outstanding': 'Outstanding',
    'no_udhaar': 'No Udhaar',
    'ledger': 'LEDGER',
    'entries': 'entries',
    'no_transactions': 'No transactions yet',
    'record_payment': 'Record Payment',
    'udhaar_credit': 'Udhaar / Credit',
    'payment_received': 'Payment Received',
    'amount_received': 'Amount Received (Rs.)',
    'enter_amount': 'Enter amount',
    'enter_valid_amount': 'Enter valid amount',
    'note_optional': 'Note (optional)',
    'save_payment': 'Save Payment',
    'outstanding_prefix': 'Outstanding: Rs. ',
    // ── Add udhaar (customer detail) ──────────────────────────────────
    'add_udhaar': 'Add Udhaar',
    'record_udhaar_title': 'Record Udhaar',
    'amount_given_label': 'Amount Given (Rs.)',
    // ── Manual item sheet ─────────────────────────────────────────────
    'manual': 'Manual',
    'manual_add_tooltip': 'Add item manually',
    'add_item_manually': 'Add Item Manually',
    'item_name': 'Item Name',
    'item_name_hint': 'e.g. Atta, Daal, Chawal',
    'item_name_required': 'Enter item name',
    'price_label': 'Price (Rs.)',
    'enter_price': 'Enter price',
    'enter_valid_price': 'Enter a valid price',
    'quantity': 'Quantity',
    'add_to_cart': 'Add to Cart',
    'no_stock_remaining': 'No stock remaining!',
    'left_in_stock': 'left in stock',
    // ── Checkout page ─────────────────────────────────────────────────
    'select_payment_method': 'SELECT PAYMENT METHOD',
    'save_to_udhaar_btn': 'Save to Udhaar (Khata)',
    'tap_to_copy': 'Tap to copy number',
    'number_copied': 'number copied!',
    'copied': 'copied!',
    'no_payment_methods':
        'No payment methods configured. Add them in Shop Details → Settings.',
    'bank_transfer': 'Bank Transfer',
    'account_title_label': 'Account Title',
    'account_no_label': 'Account No.',
    'png_any_app': 'PNG • Any app',
    'text_msg_with_items': 'Text message with items',
    'save_to_udhaar_title': 'Save to Udhaar',
    'udhaar_sheet_desc':
        'Select customer — sale will be confirmed and Rs. {amount} added to their khata.',
    'no_customers_khata': 'No customers yet. Add one from Khata.',
    'select_customer_first': 'Select a customer first',
    'save_to_name_khata': "Save to {name}'s Khata",
    'udhaar_saved_msg': "Rs. {amount} added to {name}'s khata",
    'low_stock_warning': '{n} item(s) running low on stock',
    // ── Advance / overpayment ─────────────────────────────────────────
    'advance': 'Advance',
    'paid_now_label': 'Amount Paid Now (optional)',
    'udhaar_amount_row': 'Goes to udhaar',
    'confirm_fully_paid': 'Confirm (Fully Paid)',
    'overpaid_snack': 'Rs. {extra} advance credited to {name}',
  };

  static const Map<String, String> _ur = {
    'dashboard': 'ڈیش بورڈ',
    'overview': 'جائزہ',
    'period': 'دورانیہ',
    'daily_revenue': 'روزانہ آمدنی',
    'top_products': 'مقبول اشیاء',
    'stock_alerts': 'اسٹاک الرٹ',
    'revenue': 'آمدنی',
    'orders': 'آرڈرز',
    'avg_order': 'اوسط آرڈر',
    'items': 'اشیاء',
    'low_stock': 'کم اسٹاک',
    'out_of_stock': 'اسٹاک ختم',
    'scan_barcode': 'بارکوڈ اسکین کریں',
    'align_barcode': 'بارکوڈ کو فریم میں رکھیں',
    'camera_off_title': 'کیمرہ بند ہے',
    'camera_off_subtitle': 'بارکوڈ اسکین کرنے کے لیے اپنا کیمرہ آن کریں۔',
    'turn_on_camera': 'کیمرہ آن کریں',
    'review_order': 'آرڈر چیک کریں',
    'confirm_order': 'آرڈر کی تصدیق کریں',
    'print_receipt': 'رسید پرنٹ کریں',
    'done_skip_printing': 'ہو گیا، پرنٹ نہ کریں',
    'settings': 'سیٹنگز',
    'products': 'مصنوعات',
    'shop_details': 'دکان کی تفصیلات',
    'sales_history': 'سیلز ہسٹری',
    'change_pin': 'پن تبدیل کریں',
    'print_device': 'پرنٹر ڈیوائس',
    'management': 'مینجمنٹ',
    'security': 'سیکیورٹی',
    'hardware': 'ہارڈویئر',
    'language_section': 'زبان',
    'urdu_mode': 'اردو موڈ',
    'show_app_in_urdu': 'ایپ کے متن کو اردو میں دکھائیں',
    'manage_products': 'اسٹاک اور بارکوڈز مینیج کریں',
    'edit_shop_info': 'کاروباری معلومات اور پتہ تبدیل کریں',
    'view_sales_transactions': 'گزشتہ لین دین دیکھیں',
    'update_pin': 'اپنا لاگ ان پن اپڈیٹ کریں',
    'lock_app': 'ایپ لاک کریں',
    'lock_app_description': 'پن کے ذریعے ایپ کو لاک کریں',
    'receipt_settings': 'رسید کی ترتیبات',
    'whatsapp_receipts': 'واٹس ایپ رسیدیں',
    'whatsapp_receipts_desc': 'چیک آؤٹ کے بعد واٹس ایپ شیئرنگ کے اختیارات دکھائیں',
    'no_printer_connected': 'کوئی پرنٹر منسلک نہیں',
    'connected_to_printer': 'پرنٹر سے منسلک',
    'connected_status': 'کنیکٹڈ',
    'dashboard_description': 'فروخت اور اسٹاک کا خلاصہ دیکھیں',
    'khata_description': 'گاہکوں کے ادھار اور کھاتہ کا انتظام کریں',
    'scan_to_search': 'کیمرہ اسکین کھولنے کے لیے آئیکن پر ٹیپ کریں',
    'product_management': 'پروڈکٹ مینجمنٹ',
    'search_or_scan': 'بارکوڈ تلاش کریں یا اسکین کریں',
    'tap_scanner': 'کیمرہ اسکین کھولنے کے لیے آئیکن پر ٹیپ کریں',
    'scanned_items': 'سکین کی گئی اشیاء',
    'items_total': 'اشیاء کل',
    'total_price': 'کل قیمت',
    'list_is_empty': 'فہرست خالی ہے',
    'scan_to_pay': 'ادائیگی کے لیے اسکین کریں',
    'grand_total': 'کل رقم',
    'product_name': 'پروڈکٹ کا نام',
    'price': 'قیمت',
    'total': 'کل',
    'order_confirmed_stock': 'آرڈر کی تصدیق ہوگئی! اسٹاک اپ ڈیٹ ہوگیا۔',
    'printed_successfully': 'کامیابی سے پرنٹ ہوچکا ہے!',
    'welcome_back': 'خوش آمدید',
    'create_pin': '4 ہندسے کا پن بنائیں',
    'enter_pin': 'اپنا پن درج کریں',
    'confirm_pin': 'پن کی تصدیق کریں',
    'wrong_pin': 'غلط پن۔ دوبارہ کوشش کریں۔',
    'pin_not_match': 'پن میل نہیں کھا رہے۔ دوبارہ کوشش کریں۔',
    'scan_items_instruction':
        'بارکوڈ کو اوپر کیمرہ میں اسکین کریں، آئٹمز یہاں دکھیں گے۔',
    'save_pin_success': 'پن کامیابی سے تبدیل ہوگیا',
    'enter_current_pin': 'اپنا موجودہ پن درج کریں',
    'enter_new_pin': 'اپنا نیا پن درج کریں',
    'confirm_new_pin': 'اپنے نئے پن کی تصدیق کریں',
    'change_pin_title': 'پن تبدیل کریں',
    'enter_pin_setup': 'اپنے پن کی تصدیق کریں',
    'no_products': 'کوئی مصنوعات نہیں ملی۔ کچھ شامل کریں!',
    'no_sales': 'ابھی تک کوئی سیلز نہیں',
    'scanner_left': 'بارکوڈ کو فریم میں رکھیں',
    // ── WhatsApp receipt ──────────────────────────────────────────────
    'send_receipt': 'رسید بھیجیں',
    'whatsapp_number_hint': 'گاہک کا واٹس ایپ نمبر درج کریں',
    'whatsapp_country_code_hint': 'کنٹری کوڈ شامل کریں مثلاً 923001234567',
    'whatsapp_number_empty': 'براہ کرم فون نمبر درج کریں',
    'whatsapp_number_short': 'کنٹری کوڈ کے ساتھ درست نمبر درج کریں',
    'whatsapp_not_installed': 'واٹس ایپ نہیں کھل سکا۔ کیا یہ انسٹال ہے؟',
    'cancel': 'منسوخ',
    'send': 'بھیجیں',
    'share_receipt': 'رسید شیئر کریں',
    'share_as_image': 'تصویر کے طور پر شیئر کریں',
    'whatsapp': 'واٹس ایپ',
    // ── Receipt image content ─────────────────────────────────────────
    'receipt_title': 'رسید',
    'receipt_item_header': 'آئٹم',
    'receipt_qty_header': 'تعداد',
    'receipt_price_header': 'قیمت',
    'receipt_total_header': 'کل',
    'receipt_grand_total': 'کل رقم',
    'receipt_thank_you': 'ہمارے ساتھ خریداری کا شکریہ!',
    'receipt_powered_by': 'بلنگ ایپ کے ذریعے',
    // ── Khata page ────────────────────────────────────────────────────
    'khata_title': 'کھاتہ / ادھار',
    'total_outstanding': 'کل بقایا',
    'customers': 'گاہک',
    'no_customers_yet': 'ابھی تک کوئی گاہک نہیں',
    'no_customers_desc':
        'نیچے بٹن دبائیں اور اپنا پہلا ادھار گاہک شامل کریں۔',
    'add_customer': 'گاہک شامل کریں',
    'delete_customer': 'گاہک حذف کریں؟',
    'delete_customer_confirm':
        '{name} اور ان کے تمام اندراجات حذف ہو جائیں گے۔',
    'delete': 'حذف کریں',
    'new_customer': 'نیا گاہک',
    'customer_name': 'گاہک کا نام',
    'customer_name_hint': 'مثلاً احمد بھائی',
    'customer_name_required': 'گاہک کا نام درج کریں',
    'phone_optional': 'فون (اختیاری)',
    'phone_label': 'فون نمبر',
    'phone_required': 'فون نمبر لازمی ہے',
    'phone_hint': '03XX-XXXXXXX',
    'add': 'شامل کریں',
    'udhaar': 'ادھار',
    'clear_status': 'صاف',
    // ── Customer detail page ──────────────────────────────────────────
    'outstanding': 'باقی',
    'no_udhaar': 'کوئی ادھار نہیں',
    'ledger': 'کھاتہ',
    'entries': 'اندراجات',
    'no_transactions': 'ابھی تک کوئی لین دین نہیں',
    'record_payment': 'ادائیگی ریکارڈ کریں',
    'udhaar_credit': 'ادھار / کریڈٹ',
    'payment_received': 'ادائیگی موصول',
    'amount_received': 'موصول رقم (روپے)',
    'enter_amount': 'رقم درج کریں',
    'enter_valid_amount': 'درست رقم درج کریں',
    'note_optional': 'نوٹ (اختیاری)',
    'save_payment': 'ادائیگی محفوظ کریں',
    'outstanding_prefix': 'بقایا: روپے ',
    // ── Add udhaar (customer detail) ──────────────────────────────────
    'add_udhaar': 'ادھار شامل کریں',
    'record_udhaar_title': 'ادھار ریکارڈ کریں',
    'amount_given_label': 'دی گئی رقم (روپے)',
    // ── Manual item sheet ─────────────────────────────────────────────
    'manual': 'دستی',
    'manual_add_tooltip': 'دستی آئٹم شامل کریں',
    'add_item_manually': 'دستی آئٹم شامل کریں',
    'item_name': 'آئٹم کا نام',
    'item_name_hint': 'مثلاً آٹا، دال، چاول',
    'item_name_required': 'آئٹم کا نام درج کریں',
    'price_label': 'قیمت (روپے)',
    'enter_price': 'قیمت درج کریں',
    'enter_valid_price': 'درست قیمت درج کریں',
    'quantity': 'تعداد',
    'add_to_cart': 'ٹوکری میں شامل کریں',
    'no_stock_remaining': 'اسٹاک ختم!',
    'left_in_stock': 'باقی اسٹاک',
    // ── Checkout page ─────────────────────────────────────────────────
    'select_payment_method': 'ادائیگی کا طریقہ منتخب کریں',
    'save_to_udhaar_btn': 'کھاتے میں محفوظ کریں',
    'tap_to_copy': 'نمبر کاپی کرنے کے لیے ٹیپ کریں',
    'number_copied': 'نمبر کاپی ہوگیا!',
    'copied': 'کاپی ہوگیا!',
    'no_payment_methods':
        'کوئی ادائیگی کا طریقہ ترتیب نہیں دیا۔ دکان کی تفصیلات → سیٹنگز میں شامل کریں۔',
    'bank_transfer': 'بینک ٹرانسفر',
    'account_title_label': 'اکاؤنٹ نام',
    'account_no_label': 'اکاؤنٹ نمبر',
    'png_any_app': 'پی این جی • کوئی بھی ایپ',
    'text_msg_with_items': 'اشیاء کے ساتھ پیغام',
    'save_to_udhaar_title': 'ادھار میں محفوظ کریں',
    'udhaar_sheet_desc':
        'گاہک منتخب کریں — آرڈر کی تصدیق ہوگی اور روپے {amount} ان کے کھاتے میں شامل ہوں گے۔',
    'no_customers_khata': 'ابھی تک کوئی گاہک نہیں۔ کھاتے سے شامل کریں۔',
    'select_customer_first': 'پہلے گاہک منتخب کریں',
    'save_to_name_khata': '{name} کے کھاتے میں محفوظ کریں',
    'udhaar_saved_msg': 'روپے {amount} {name} کے کھاتے میں شامل ہوگئے',
    'low_stock_warning': '{n} آئٹمز کا اسٹاک کم ہے',
    // ── Advance / overpayment ─────────────────────────────────────────
    'advance': 'پیشگی',
    'paid_now_label': 'ابھی ادا کی گئی رقم (اختیاری)',
    'udhaar_amount_row': 'ادھار میں جائے گا',
    'confirm_fully_paid': 'تصدیق کریں (مکمل ادائیگی)',
    'overpaid_snack': 'روپے {extra} {name} کے پیشگی میں شامل ہوگئے',
  };

  static String translate(BuildContext context, String key,
      {bool listen = true}) {
    final language = listen
        ? context.watch<LanguageCubit>().state
        : context.read<LanguageCubit>().state;
    return (language == AppLanguage.urdu ? _ur : _en)[key] ?? _en[key] ?? key;
  }
}

extension TranslateExtension on BuildContext {
  /// Use inside build() — watches for language changes and rebuilds.
  String tr(String key) => AppLocalizations.translate(this, key);

  /// Use inside listeners, onPressed, callbacks — reads once, no rebuild.
  String trOnce(String key) =>
      AppLocalizations.translate(this, key, listen: false);

  bool get isUrdu => watch<LanguageCubit>().state == AppLanguage.urdu;
}
